### ISSUE TITLE
Support-v4 22 not working with robolectric 2.4 - NoClassDefFoundErrors

### ISSUE THREAD

**Issue by sriharim25** [robolectric/robolectric#1789]
We are using Robolectric 2.4 for our project with 
```
compileSdkVersion = 19
buildToolsVersion = "19.1.0"
```

Our tests are configured to ```unitTestCompile support-v4``` and 
```
unitTestCompile (robolectric:2.4) {
   exclude module: 'support-v4'
}
```

The support-v4 class references are failing with ```android.content.res.Resources$NotFoundException: Resource ID #0x7f100004``` or with 

```
Caused by: java.lang.NoClassDefFoundError: android/support/v4/view/LayoutInflaterFactory
```

**Comment by erd** [comment]
Please upgrade to 3.0. Robolectric no longer depends directly on support-v4, so this will more than likely solve your problem.
