### ISSUE TITLE
Tests fail with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by DummyCo** [robolectric/robolectric#5092]
### Description
Tests fail on 4.3 with
` java.lang.NoSuchMethodError: androidx.test.runner.MonitoringInstrumentation.restoreUncaughtExceptionHandler()V`
Works fine with 4.2.1

Stacktrace:
```
java.lang.NoSuchMethodError: androidx.test.runner.MonitoringInstrumentation.restoreUncaughtExceptionHandler()V

	at org.robolectric.android.fakes.RoboMonitoringInstrumentation.finish(RoboMonitoringInstrumentation.java:163)
	at org.robolectric.android.internal.AndroidTestEnvironment.tearDownApplication(AndroidTestEnvironment.java:463)
	at org.robolectric.RobolectricTestRunner.afterTest(RobolectricTestRunner.java:313)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Robolectric & Android Version
Android Version: 28
Robolectric: 4.3

**Comment by brettchabot** [comment]
Can you post your build.gradle? It sounds like the build might be picking up the wrong androidx.test.monitor version  - it should be 1.2.0

**Comment by DummyCo** [comment]
Seems like dependency resolution for `androidx.test.monitor` solves problem indeed 👍 :
```
configurations.all {
  resolutionStrategy {
    force group: 'androidx.test', name: 'monitor', version: '1.2.0'
  }
}
```
Old `test.monitor` was pulled here:

![bmFtI0Cl1P](https://user-images.githubusercontent.com/3989453/59263723-4a16fd80-8c4a-11e9-8472-2560a19e0679.png)

Thank you, @brettchabot!

**Comment by brettchabot** [comment]
Right, if you're using Robolectric 4.3 you should be using Androidx Test 1.2.0. So if I were you I'd update to androidx.test:core:1.2.0

**Comment by slott** [comment]
This is what I'm getting when running tests from within Android Studio - but not from the command line... Any idea how that can be ?

I'm on  Androidx Test 1.2.0 as well - so not getting what could be the problem behind this...

**Comment by nseidm1** [comment]
I'm stuck as well. Activities work fine, but for fraggies:

java.lang.NoSuchMethodError: androidx.test.runner.MonitoringInstrumentation.restoreUncaughtExceptionHandler()V

`testImplementation 'androidx.test:core:1.2.0'
  debugImplementation 'androidx.fragment:fragment-testing:1.1.0-beta01'
  testImplementation 'com.android.support.test:runner:1.0.2'
  testImplementation 'org.robolectric:robolectric:4.3'`

**Comment by DummyCo** [comment]
@slott @nseidm1 did you guys tried to inspect your resolved dependency trees and forcing exact version via `resolutionStrategy`?

**Comment by XiaoTao6** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "jp.co.goodf.jlite"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        useLibrary 'android.test.runner'
        useLibrary 'android.test.base'
        useLibrary 'android.test.mock'
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField("String", "BASE_URL", "\"${DEBUG_BASE_URL}\"")
    }
    testOptions{
        unitTests.returnDefaultValues = true
        unitTests.all {
            // All the usual Gradle options.
            testLogging {
                events "passed", "skipped", "failed", "standardOut", "standardError"
                outputs.upToDateWhen { false }
                showStandardStreams = true
            }
        }
        unitTests.includeAndroidResources = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField("String", "BASE_URL", "\"${RELEASE_BASE_URL}\"")
        }
        debug {
            applicationIdSuffix ".debug"
            debuggable true
        }
        staging {
            initWith debug
            applicationIdSuffix ".debugStaging"
            buildConfigField("String", "BASE_URL", "\"${STAGING_BASE_URL}\"")
            debuggable true
        }
        develop {
            initWith debug
            applicationIdSuffix ".debugDevelop"
            buildConfigField("String", "BASE_URL", "\"${DEVELOP_BASE_URL}\"")
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    flavorDimensions "version"
    productFlavors {
        facility {
            dimension "version"
            applicationIdSuffix ".facility"
            versionNameSuffix "-facility"
        }
        seller {
            dimension "version"
            applicationIdSuffix ".seller"
            versionNameSuffix "-seller"
        }
    }
}

dependencies {

    implementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'


    testImplementation 'junit:junit:4.12'
    testImplementation  'androidx.test:core:1.2.0'


    // AndroidJUnitRunner and JUnit Rules
    androidTestImplementation 'androidx.test:runner:1.1.0'
    testImplementation  'androidx.test:rules:1.1.0'

    // Assertions
    androidTestImplementation 'androidx.test.ext:junit:1.0.0'
    androidTestImplementation 'androidx.test.ext:truth:1.0.0'
    androidTestImplementation 'com.google.truth:truth:0.42'

    // Espresso dependencies
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'

    androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-accessibility:3.1.0'
    androidTestImplementation 'androidx.test.espresso:espresso-web:3.1.0'
    androidTestImplementation 'androidx.test.espresso.idling:idling-concurrent:3.1.0'

    // The following Espresso dependency can be either "implementation"
    // or "androidTestImplementation", depending on whether you want the
    // dependency to appear on your APK's compile classpath or the test APK
    // classpath.
    androidTestImplementation 'androidx.test.espresso:espresso-idling-resource:3.1.0'


    //mockito
    testImplementation "org.mockito:mockito-core:2.8.9"
    //powermock
    testImplementation "org.powermock:powermock-module-junit4:1.7.4"
    testImplementation "org.powermock:powermock-api-mockito2:1.7.4"
    testImplementation "org.powermock:powermock-module-junit4-rule:1.7.4"
    testImplementation "org.powermock:powermock-classloading-xstream:1.7.4"

    //robolectric
    testImplementation "org.robolectric:robolectric:4.3"
    testImplementation 'org.robolectric:android-all:4.1.2_r1-robolectric-0'
    // retrofit2
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-jackson:2.5.0'
    // butterknife
    implementation 'com.jakewharton:butterknife:10.1.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.1.0'
    annotationProcessor 'org.projectlombok:lombok:1.16.20'
    compileOnly 'org.projectlombok:lombok:1.16.20'
    implementation files('libs/tickethub-api-dto.jar')
    implementation files('libs/goodf-commons.jar')
    implementation files('libs/tickethub-front-api-dto.jar')
    implementation 'org.apache.commons:commons-lang3:3.8.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.9.9'
    implementation 'com.google.zxing:core:3.3.3'

}


I need help with the same mistake!

**Comment by XiaoTao6** [comment]
@brettchabot @DummyCo

**Comment by XiaoTao6** [comment]
Thank you very much. I solved it.

**Comment by KarolMB** [comment]
@XiaoTao6 If You will tell **how** You solve this problem it could be helpful for other persons : )

**Comment by Kisty** [comment]
@KarolMB see https://github.com/robolectric/robolectric/issues/5092#issuecomment-500777911

**Comment by mochadwi** [comment]
> Seems like dependency resolution for `androidx.test.monitor` solves problem indeed 👍 :
> 
> ```
> configurations.all {
>   resolutionStrategy {
>     force group: 'androidx.test', name: 'monitor', version: '1.2.0'
>   }
> }
> ```
> 
> Old `test.monitor` was pulled here:
> 
> ![bmFtI0Cl1P](https://user-images.githubusercontent.com/3989453/59263723-4a16fd80-8c4a-11e9-8472-2560a19e0679.png)
> 
> Thank you, @brettchabot!

This fixed my issue. And it's recommended to update your `androidx.test:core` to `1.2.0`. As stated here from @brettchabot

> Right, if you're using Robolectric 4.3 you should be using Androidx Test 1.2.0. So if I were you I'd update to androidx.test:core:1.2.0

**Comment by carstenhag** [comment]
So why do we need to add those `configurations.all` lines? Can't the dependency resolution be fixed? I hope you understand me that I don't want to have this in my codebase for years to come 😄

**Comment by carstenhag** [comment]
Still getting `NoSuchMethodError`s, but I think this is being caused by the #4776 :/.
