### ISSUE TITLE
ShadowExtractor

### ISSUE THREAD

**Issue by slott** [robolectric/robolectric#3339]
### Description
When upgrading from version 3.3 to 3.4 I get this error for all of my tests
    java.lang.NoClassDefFoundError: org/robolectric/internal/ShadowExtractor

### Steps to Reproduce
Upgrade from 3.3 to 3.4 and re-run tests

### Robolectric & Android Version
Tried version 3.4.1 and 3.4.2 as well as various versions of the shadow classes

**Comment by jongerrish** [comment]
Check the release notes, this had been deprecated and removed. Switch to Shadows.extract()

**Comment by ckitterl** [comment]
Shadows.extract() or

> Check the release notes, this had been deprecated and removed. Switch to Shadows.extract()

Shadows.extract() or Shadow.extract() ? 

I use 4.1 and  custom shadow class work well but Shadow.extract(CustomShadowClass.class) throw `java.lang.Class cannot be cast to org.robolectric.internal.bytecode.ShadowedObject ` error
