### ISSUE TITLE
java.lang.NoSuchMethodException: android.app.Instrumentation.init and other occasional issues

### ISSUE THREAD

**Issue by realdadfish** [robolectric/robolectric#6038]
This is Robolectric 4.5-alpha-2, JDK 11, targetSdk 29

On CI occasionally a test fails with

```
[09:27:22] java.lang.NoSuchMethodException: android.app.Instrumentation.init(android.app.ActivityThread, android.content.Context, android.content.Context, android.content.ComponentName, android.app.IInstrumentationWatcher, android.app.IUiAutomationConnection)
[09:27:22] at java.base/java.lang.Class.getDeclaredMethod(Class.java:2475)
[09:27:22] at org.robolectric.shadows.ShadowInstrumentation$_Instrumentation_$$Reflector7.init(Unknown Source)
[09:27:22] at org.robolectric.android.internal.AndroidTestEnvironment.createInstrumentation(AndroidTestEnvironment.java:473)
[09:27:22] at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:232)
[09:27:22] at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:171)
[09:27:22] at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
[09:27:22] at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
[09:27:22] at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[09:27:22] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[09:27:22] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[09:27:22] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[09:27:22] at java.base/java.lang.Thread.run(Thread.java:834)
```

When I retry the build, it might go through or alternatively fail with another error (which is already mentioned in #5082)

```
[10:17:36] java.lang.NoClassDefFoundError: [Landroid/content/res/ApkAssets;
[10:17:36] at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[10:17:36] at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
[10:17:36] at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
[10:17:36] at java.base/java.lang.Class.getMethods(Class.java:1904)
[10:17:36] at org.robolectric.util.reflector.ReflectorClassWriter.write(ReflectorClassWriter.java:95)
[10:17:36] at org.robolectric.util.reflector.Reflector.getBytecode(Reflector.java:152)
[10:17:36] at org.robolectric.util.reflector.Reflector.createReflectorClass(Reflector.java:106)
[10:17:36] at org.robolectric.util.reflector.Reflector.reflector(Reflector.java:65)
[10:17:36] at org.robolectric.util.reflector.Reflector.reflector(Reflector.java:49)
[10:17:36] at org.robolectric.shadows.ShadowArscAssetManager10.reset(ShadowArscAssetManager10.java:238)
[10:17:36] at org.robolectric.Shadows.reset(Shadows.java:2323)
[10:17:36] at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:518)
[10:17:36] at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:349)
[10:17:36] at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
[10:17:36] at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:347)
[10:17:36] at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:272)
[10:17:36] at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
[10:17:36] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[10:17:36] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[10:17:36] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[10:17:36] at java.base/java.lang.Thread.run(Thread.java:834)
[10:17:36] 
[10:17:36] Caused by:
[10:17:36] java.lang.ClassNotFoundException: android.content.res.ApkAssets
[10:17:36] at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:163)
[10:17:36] at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:129)
[10:17:36] at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:115)
[10:17:36] at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
[10:17:36] at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:115)
[10:17:36] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[10:17:36] ... 21 more
```

The CI environment is stateless, i.e. a new container is spawned for every execution. Would you have any idea how to track down issues like this? Is there a way to debug-print the classpath Robolectric uses, in order to check for ordering issues / missing things?

**Comment by hoisie** [comment]
These error messages are bizarre, especially the second one. Interesting that it happens using reflector. If this is something you want to track down I would be happy to add some additional logging. I think the two pieces of relevant information are 1) What are the API levels set and 2) which classloaders are being used when defining the reflector classes.

**Comment by realdadfish** [comment]
Yes, I'd definitely enable more suitable logging on CI / use a logging-intensive debug build, to track these down if they occur again.

**Comment by hoisie** [comment]
I spent some time looking into this issue and wanted to report some findings.

The first issue stack trace is bizarre to me. Unfortunately that crash occurs in the class generated during runtime, so to add additional logging, it would require emitting bytecode for the try/catch/log. At first I thought it was a caching issue (since generated reflector classes are cached), but I am really sure.

The second crash `java.lang.ClassNotFoundException: android.content.res.ApkAssets` seems more straightforward to me. Looking at the stack trace, that is called in a `@Resetter` method, and that call originates from here:

https://source.corp.google.com/piper///depot/google3/third_party/java_src/robolectric/junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java;l=270-275?q=SandboxTestRunner&sq=package:piper%20file:%2F%2Fdepot%2Fgoogle3%20-file:google3%2Fexperimental

Just before the resetters are invoked, there is a call to:

```
Thread.currentThread().setContextClassLoader(priorContextClassLoader);
```

It's possible that trying to load the `android/content/res/ApkAssets` in a class loader that does not exist.

I'd still like to track down these issues, but since I'm not an expert on the reflector system, we can always switch to using ReflectionHelpers/directlyOn until we get a clearer picture of what's happening.

**Comment by hoisie** [comment]
One possibility that would cause both of these issues is that the value of `RuntimeEnvironment.getApiLevel()` is incorrect and does not match with the actual Android Sandbox that is being used.

**Comment by hoisie** [comment]
@realdadfish do you have a repro of these issue(s)? Even if it's intermittent? Seems like it may be a race condition, or possibly the android-all jars are messed up? There are a few possibilities, but I don't want to start making changes without knowing the root cause. I would definitely be interested in finding out what's going on here, though.

**Comment by hoisie** [comment]
Also, for this type of issue, I'd probably start adding log statements everywhere and using custom 4.5-SNAPSHOT builds. I  would probably add logging inside of AndroidTestEnvironment where `RuntimeEnvironment` is initialized. Also, if this exception occurs, it would be interesting to see what are the Android environment properties (e.g. api level, binary resource mode, looper mode). There is not this type of built-in logging for Robolectric at the moment.

**Comment by realdadfish** [comment]
Unfortunately not, anymore. The failures were random and the project also ended for me last week, so I don't have access to the CI anymore. I'll keep an eye on this issue and eventually use the logging facility (if there will be any) in my next project that starts in January.

Sorry for not being of more help 😞

Am 17. November 2020 06:20:58 MEZ schrieb Michael Hoisie <notifications@github.com>:
>@realdadfish do you have a repro of these issue(s)? Even if it's
>intermittent? Seems like it may be a race condition, or possibly the
>android-all jars are messed up? There are a few possibilities, but I
>don't want to start making changes without knowing the root cause. I
>would definitely be interested in finding out what's going on here,
>though.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/robolectric/robolectric/issues/6038#issuecomment-728692986

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
