### ISSUE TITLE
noSuchMethodError - setLibraryManifests after migration from 3.0 to 3.3.2

### ISSUE THREAD

**Issue by yodutouf** [robolectric/robolectric#3131]
### Description

I migrate several projects from version 3.0 to version 3.3.2.

Just for one project, I get

```
java.lang.NoSuchMethodError: org.robolectric.manifest.AndroidManifest.setLibraryManifests
at org.robolectric.internal.MavenManifestFactory.create(MavenManifestFactory.java:62)
at org.robolectric.RobolectricTestRunner.getAppManifest(RobolectricTestRunner.java:373)
at org.robolectric.RobolectricTestRunner.getChildren(RobolectricTestRunner.java:215)
```

I check several times my gradle configuration. I don't see any difference with other projects and I am using a basic configuration

```
@Config(sdk = 18)
@RunWith(RobolectricTestRunner.class)
```

Do you have any clue ?

**Comment by hoisie** [comment]
Have you tried doing

```java
@Config(sdk = 18, constants=BuildConfig.class)
```

**Comment by yodutouf** [comment]
Yes, 
I try as well with 

`@Config(sdk = 18, constants=BuildConfig.class, manifest="AndroidManifest.xml")`

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
