### ISSUE TITLE
Issue with 3.1-SNAPSHOT

### ISSUE THREAD

**Issue by ksprash** [robolectric/robolectric#2403]
I was able to build and run tests successfully when using robolectric:3.0. But after upgrading to 3.1-SNAPSHOT facing an issue with ant dependencies as below.

java.lang.NoClassDefFoundError: org/apache/tools/ant/Project
	at org.robolectric.internal.dependency.MavenDependencyResolver.<init>(MavenDependencyResolver.java:15)
	at org.robolectric.internal.dependency.MavenDependencyResolver.<init>(MavenDependencyResolver.java:20)
	at org.robolectric.RobolectricTestRunner.getJarResolver(RobolectricTestRunner.java:102)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.Project
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

**Comment by ksprash** [comment]
I had to reorder the maven repo url in build.gradle and then all the dependencies of Robolectric were fetched.
