### ISSUE TITLE
Could not initialize class android.graphics.Canvas

### ISSUE THREAD

**Issue by Kisty** [robolectric/robolectric#2692]
### Description
Fails on tests which use Fragments. Was working fine on Robolectric `3.1.2` until I tried upgrading to `3.1.4`. Reverting to `3.1.2` isn't working anymore. Tried gradlew clean and removing artifacts from `.m2/` folder.

### Steps to Reproduce
Possibly by referencing a `android.support.v7.widget.DividerItemDecoration` (only available in `recyclerview-v7:25.0.0` on a `RecyclerView` on a Fragment in the `main/` java source directory.

`gradlew clean :app:testDevDebugUnitTest`

Interestingly, running the tests in Android Studio did work for a bit (by right clicking package>Run tests). Now it does not.

### Robolectric & Android Version
Robolectric: 3.1.4
Android 25 (using sdk = 23 on tests)
Support library version: 25.0.0

Possibly related to #2594

```
java.lang.NoClassDefFoundError: Could not initialize class android.graphics.Canvas
	at android.view.View.__constructor__(View.java:3804)
	at android.view.View.<init>(View.java)
	at android.view.ViewGroup.<init>(ViewGroup.java)
	at android.widget.FrameLayout.<init>(FrameLayout.java)
	at com.android.internal.policy.PhoneWindow$DecorView.<init>(PhoneWindow.java)
	at com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:3630)
	at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3973)
	at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
	at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:371)
	at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:320)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:281)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
	at uk.co.imagitech.learn2.hp.VideoActivity.onCreate(VideoActivity.java:115)
	at android.app.Activity.performCreate(Activity.java:6237)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:126)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:356)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at org.robolectric.util.ActivityController.create(ActivityController.java:133)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:227)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:102)
	at uk.co.imagitech.learn2.hp.CheatFragmentTest.startFragment(CheatFragmentTest.java:111)
	at uk.co.imagitech.learn2.hp.CheatFragmentTest.cheatPatterned_showsReason(CheatFragmentTest.java:82)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:498)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:171)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:137)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Kisty** [comment]
Related to #1932

**Comment by Kisty** [comment]
Closing...
