### ISSUE TITLE
NoClassDefFoundError: androidx/test/platform/app/InstrumentationRegistry when upgrade from 3.8 to 4.13

### ISSUE THREAD

**Issue by juherr** [robolectric/robolectric#9492]
### Description

I'm trying to build the https://github.com/joelittlejohn/jsonschema2pojo/pull/1599 under JDK11 and later.

Robolectric 3.8 doesn't work with JDK11. I suppose it is because the included ASM is too old:
```
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.robolectric.internal.bytecode.ClassNodeProvider.createClassNode(ClassNodeProvider.java:24)
	at org.robolectric.internal.bytecode.ClassNodeProvider.getClassNode(ClassNodeProvider.java:16)
	at org.robolectric.internal.bytecode.ClassInstrumentor.isOverridingFinalMethod(ClassInstrumentor.java:218)
	at org.robolectric.internal.bytecode.ClassInstrumentor.createInstrumentableMethodIfNotAlreadyPresent(ClassInstrumentor.java:236)
	at org.robolectric.internal.bytecode.ClassInstrumentor.instrument(ClassInstrumentor.java:105)
	... 34 more
```
https://github.com/joelittlejohn/jsonschema2pojo/actions/runs/10416696319/job/28849441670#step:3:2883

After upgrading to 4.13, the project is still failing under JDK11 because NoClassDefFoundError:
```
java.lang.NoClassDefFoundError: androidx/test/platform/app/InstrumentationRegistry
	at org.robolectric.android.internal.AndroidTestEnvironment.clearEnvironment(AndroidTestEnvironment.java:624)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:155)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:283)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:285)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
https://github.com/joelittlejohn/jsonschema2pojo/actions/runs/10418012674/job/28853332058?pr=1599#step:4:4906

The project is using Maven as the build tool.

I found nothing in the documentation, changelogs, or issues explaining why this is happening and how to fix it.

### Steps to Reproduce
Fork my branch and let GitHub Actions do its job.

### Robolectric & Android Version
Robolectric: 4.13

### Link to a public git repo demonstrating the problem:
https://github.com/joelittlejohn/jsonschema2pojo/pull/1599

**Comment by MGaetan89** [comment]
You're probably missing the following dependency: https://maven.google.com/web/index.html#androidx.test:monitor

@utzcoz @hoisie shouldn't this be exposed by Robolectric if it is used?

**Comment by juherr** [comment]
@MGaetan89 @utzcoz Thank you for your prompt response. 
After attempting alternative approaches without success, I believe it would be more practical to adhere closely to the standards and use Gradle for Android testing.

In the interest of transparency, I suggest that the documentation explicitly specify that Maven is no longer supported (source: https://robolectric.org/getting-started/#building-with-maven).

Regarding JDK8, I plan to keep the existing tests which use the old Robolectric framework when run with JDK8 as they are currently functioning.
Alternatively, I may also suggest discontinuing support for JDK8.

**Comment by MGaetan89** [comment]
@hoisie @utzcoz is it official that Maven is no longer supported? Or is it an issue to fix?
If it is still supported, maybe we could look into updating [this repo](https://github.com/robolectric/deckard-maven) to have an up-to-date Robolectric project built with Maven to ensure that the compatibility is maintained?

@juherr I'm reopening this issue until the situation is clarified.

**Comment by MGaetan89** [comment]
I was able to reproduce this issue by updating [`deckard-maven`](https://github.com/robolectric/deckard-maven). So the issue probably is on Robolectric's side.
As @utzcoz said, it's probably linked to the fact that some dependencies are in the AAR format, as it can be seen here:
https://github.com/robolectric/robolectric/blob/bff2bedb8a660a9f71540b87b1ab2ac17269d1e3/build.gradle.kts#L5-L11

**Comment by J3riie** [comment]
Hello guys,
I am currently working on a Gradle project with Robolectric, and I have the exact same issue, even though I am running the tests on a Gradle environment. 
I am declaring androidx.test:monitor dependency explicitly as testImplementation, and I successfully find platform/app/InstrumentationRegistry in the aar, but still get the "java.lang.NoClassDefFoundError: androidx/test/platform/app/InstrumentationRegistry" error. One of my guesses is that I applied the java plugin into my project, and that might be a no go for such dependencies ?

I'm out of ideas and need your help !
