### ISSUE TITLE
java.lang.NoClassDefFoundError: android/content/pm/PackageInstaller$PreapprovalDetails

### ISSUE THREAD

**Issue by jdckr** [robolectric/robolectric#9746]
### Description
Hi,

I am getting the following error and don't know how to resolve it.
I am using robolectric 4.13 and Sdk Version 33. The code is working fine with robolectric 4.9 and Sdk Version 29.

Any hints how to resolve it? Thanks in advance.

```
android/content/pm/PackageInstaller$PreapprovalDetails
java.lang.NoClassDefFoundError: android/content/pm/PackageInstaller$PreapprovalDetails
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodDeclaredOnClass(ShadowWrangler.java:309)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethod(ShadowWrangler.java:282)
	at org.robolectric.internal.bytecode.ShadowWrangler.pickShadowMethod(ShadowWrangler.java:258)
	at org.robolectric.internal.bytecode.ShadowWrangler.lambda$findShadowMethodHandle$0(ShadowWrangler.java:184)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:51)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodHandle(ShadowWrangler.java:178)
	at org.robolectric.internal.bytecode.RobolectricInternals.findShadowMethodHandle(RobolectricInternals.java:31)
	at org.robolectric.internal.bytecode.InvokeDynamicSupport.bindCallSite(InvokeDynamicSupport.java:185)
	at org.robolectric.internal.bytecode.InvokeDynamicSupport.lambda$bootstrap$1(InvokeDynamicSupport.java:106)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:51)
	at org.robolectric.internal.bytecode.InvokeDynamicSupport.bootstrap(InvokeDynamicSupport.java:94)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:166)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
	at android.content.pm.PackageInstaller$Session.<init>(PackageInstaller.java:1022)
	at org.robolectric.shadows.ShadowPackageInstaller.openSession(ShadowPackageInstaller.java:145)
	at android.content.pm.PackageInstaller.openSession(PackageInstaller.java)
	at UpdateService.installApk(UpdateService.java:115)
	at UpdateService.triggerUpdate(UpdateService.java:104)
```

**Comment by jdckr** [comment]
This does work.

Is there any compatibility matrix or is it a bug that those versions don't work together?
