### ISSUE TITLE
Robolectric 4.16 fails to load third-party classes (LogFactory) in Android Library unit tests

### ISSUE THREAD

**Issue by ibartj** [robolectric/robolectric#10590]
### Description
After upgrading to Robolectric 4.16, unit tests in our Android library module that depend on `commons-logging` fail with `ClassNotFoundException: org.apache.commons.logging.LogFactory`. This worked correctly in Robolectric 4.15.1.

### Steps to Reproduce
Create an Android library module.

Add dependency:

```
implementation("commons-logging:commons-logging:1.2")
testImplementation("commons-logging:commons-logging:1.2")
testImplementation("org.robolectric:robolectric:4.16")
```

Write a Robolectric unit test that initializes a class depending on `org.apache.commons.logging.LogFactory` (for example `org.apache.xml.security.Init`).

Run the test.

Alternatively, you can just try to type `org.apache.commons.logging.` in the IDE and it won't be resolved as a valid namespace.

### Robolectric & Android Version
The test should pass and the class `LogFactory` should be available in the Robolectric sandbox classloader.

### Actual behavior:
The test fails with:

```
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
...
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
```

### Workarounds tested:

Adding `androidTestImplementation("commons-logging:commons-logging:1.2")`
Adding `@Config(instrumentedPackages = ["org.apache.commons.logging"])`
Adding `configurations.all { resolutionStrategy { force "commons-logging:commons-logging:1.2" } }`
Adding `instrumentedPackages=org.apache.commons.logging` into `robolectric.properties`
Adding `commons-logging-1.2.jar` as a file dependency → **works correctly**
Downgrading to Robolectric 4.15.1 → **works correctly**

### Environment:

Android Gradle Plugin: 8.12.1
Gradle: 9.0.0
JDK: 17
Android Studio Narwhal Feature Drop | 2025.1.2 Patch 1

**Comment by hoisie** [comment]
A git bisect could be useful here.
