### ISSUE TITLE
Android Annotation Framework using robolectric 3.8 get error

### ISSUE THREAD

**Issue by tonyyang924** [robolectric/robolectric#3925]
### Description
my project using android annotation framework 4.4
i wanna use Robolectric framework to execute unit test
but always get NoSuchMethodError

### Steps to Reproduce
`@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class)
public class PresenterTest {

    MainActivity_ activity;
    Contract.View view;
    
    @Before
    public void setUp() throws Exception {
        activity = Robolectric.buildActivity(MainActivity_.class).create().get();

        ....
    }

    @Test
    public void shouldPass() {
        Assert.assertEquals(true, ((MockView) view).isNonEmptyTitle);
    }
`
    
### Robolectric & Android Version

Android studio 3.0+
Robolectric 3.8
Android project target version 27
Android Annotation Version 4.4

### Link to a public git repo demonstrating the problem:

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Exception in thread "main" java.lang.NoSuchMethodError: org.robolectric.annotation.Config$Builder.defaults()Lorg/robolectric/annotation/Config$Builder;
	at org.robolectric.ConfigMerger.getConfig(ConfigMerger.java:38)
	at org.robolectric.RobolectricTestRunner.getConfig(RobolectricTestRunner.java:475)
	at org.robolectric.RobolectricTestRunner.getChildren(RobolectricTestRunner.java:254)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
	at com.intellij.junit4.JUnit4IdeaTestRunner.getDescription(JUnit4IdeaTestRunner.java:78)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

**Comment by jongerrish** [comment]
Looks like you have some mismatched Robolectric jars. I.e. not all the same
version. All Robolectric jars should be the same version. Try clearing your
caches?
