### ISSUE TITLE
Compilation Issue with Robolectric 4.4-SNAPSHOT

### ISSUE THREAD

**Issue by kingargyle** [robolectric/robolectric#5636]
### Description
When trying to compile a test that worked fine with Robolectric 4.3.1, I'm getting a compilation error with Robolectric 4.4 complaining about a missing android.app.role.RoleManager

This test uses a shadow and tries to get the shadowOf an activity.

If you switch the library back to 4.3.1, everything compiles and executes as expected.

### Steps to Reproduce

Try to get a ShadowOf.shadows(activity).

### Robolectric & Android Version

4.4-SNAPSHOT

Compile SDK 28
Min sdk 21

### Link to a public git repo demonstrating the problem:

https://github.com/NineWorlds/serenity-android/tree/robo44

Compilation issue:

serenity-app/src/test/java/us/nineworlds/serenity/ui/browser/movie/MovieCategorySpinnerOnItemSelectedListenerTest.java:97: error: cannot access RoleManager

**Comment by kingargyle** [comment]
This seems to be because I had the compile version set to 28.  If I set the compile version to 29, then we get past these compilation issues..

**Comment by brettchabot** [comment]
Yes, Robolectric 4.4-SNAPSHOT requires compile sdk set to 29. In general, Robolectric @ head will always compile against latest release SDK.
