### ISSUE TITLE
Sqlite exceptions when upgrading to 4.11.1

### ISSUE THREAD

**Issue by edenman** [robolectric/robolectric#8754]
```
Caused by: java.lang.NoSuchMethodError: 'java.nio.file.Path org.robolectric.util.TempDirectory.getBasePath()'
	at org.robolectric.nativeruntime.DefaultNativeRuntimeLoader.maybeCopyFonts(DefaultNativeRuntimeLoader.java:136)
	at org.robolectric.nativeruntime.DefaultNativeRuntimeLoader.lambda$ensureLoaded$0(DefaultNativeRuntimeLoader.java:81)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:86)
	at org.robolectric.nativeruntime.DefaultNativeRuntimeLoader.ensureLoaded(DefaultNativeRuntimeLoader.java:74)
	at org.robolectric.nativeruntime.DefaultNativeRuntimeLoader.injectAndLoad(DefaultNativeRuntimeLoader.java:54)
	at org.robolectric.shadows.ShadowNativeSQLiteConnection.nativeOpen(ShadowNativeSQLiteConnection.java:26)
	at org.robolectric.shadows.ShadowNativeSQLiteConnection.nativeOpen(ShadowNativeSQLiteConnection.java:50)
	at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:763)
	at android.database.sqlite.SQLiteDatabase.createInMemory(SQLiteDatabase.java:959)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:368)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
```

Also:
```
Caused by: java.lang.UnsatisfiedLinkError: 'long org.robolectric.nativeruntime.SQLiteConnectionNatives.nativeOpen(java.lang.String, int, java.lang.String, boolean, boolean, int, int)'
	at org.robolectric.nativeruntime.SQLiteConnectionNatives.nativeOpen(Native Method)
	at org.robolectric.shadows.ShadowNativeSQLiteConnection.lambda$nativeOpen$0(ShadowNativeSQLiteConnection.java:32)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.shadows.ShadowNativeSQLiteConnection.nativeOpen(ShadowNativeSQLiteConnection.java:28)
	at org.robolectric.shadows.ShadowNativeSQLiteConnection.nativeOpen(ShadowNativeSQLiteConnection.java:50)
	at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:763)
	at android.database.sqlite.SQLiteDatabase.createInMemory(SQLiteDatabase.java:959)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:368)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
```

### Robolectric & Android Version
Upgrading from 4.7.3 (😬) to 4.11.1
compileSdkVersion=34, targetSdkVersion=33, minSdkVersion = 26
androidJar: org.robolectric:android-all:14-robolectric-10818077

**Comment by hoisie** [comment]
What is the os and CPU architecture?

Do you have a repro?

**Comment by edenman** [comment]
Macbook Pro, M1 Max.  No repro, it's in a huge internal project.  I can try to make one next week

**Comment by hoisie** [comment]
@edenman my initial reaction is that you may have multiple copies of Robolectric on the classpath. The method `'java.nio.file.Path org.robolectric.util.TempDirectory.getBasePath()'` was added in 4.10 (https://github.com/robolectric/robolectric/commit/82454a29bee6995cbb76e791193dbe5f083bb766). So if this method is not present, it means you may still have some Robolectric 4.7 artifacts. I would examine your runtime classpath and figure out if there are any jar files that contain Robolectric code.

**Comment by edenman** [comment]
That was absolutely it, thanks!
