### ISSUE TITLE
Regression when upgrading from 4.0 causes java.lang.NoClassDefFoundError: androidx/test/runner/MonitoringInstrumentation

### ISSUE THREAD

**Issue by bj0** [robolectric/robolectric#6171]
### Description
I'm working on a project that has a module in it that's an "android" java-library (not android library).  It's configured with:

```
apply plugin: 'java-library'

...

dependencies {
    androidJar = fileTree(dir: "$androidHome/platforms/android-29", includes: ['android.jar'])
    ...
    compileOnly androidJar
    ...
    testImplementation androidJar
    testImplementation "junit:junit:$junitVersion"
    testImplementation "org.robolectric:robolectric:$robolectricVersion"
```

This library has a few unit tests that use framework objects (Color and Bitmap mostly), so they use the RobolectricTestRunner:

```
@RunWith(RobolectricTestRunner.class)
public class CanonicalImageCacheTests
{
    @Test
    public void testBasicProperties()
    {
         ...
```

They run fine under Robolectric 4.0, but as soon as I bump the version to 4.1,4.2, 4.3 or 4.4, the tests fail with:

```
Caused by: java.lang.ClassNotFoundException: androidx.test.runner.MonitoringInstrumentation
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:163)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:118)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:111)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:110)
```

Is a java-library module no longer supported?  Was it just a fluke that it worked before?

I'm using Android Studio and gradle plugin 4.1.1

**Comment by hoisie** [comment]
I would suggest creating a new boilerplate project with Android studio and model your project's build.gradle on that. The problem is likely how your build.gradle is structured.

**Comment by bj0** [comment]
@hoisie The problem is that it's not a normal android module or project.  It's part of a larger "plugin" project that is loaded with a custom plugin loading system.  Because of these odd circumstances there are restrictions on the build config (like it *has* to be a .jar).

I was just hoping that someone had seen this specific error or knew of a workaround (besides reverting to 4.0).

**Comment by bj0** [comment]
I'm still getting this in 4.5.1.

Additionally updates to AGP have made version 4.0 start producing:

```
WARNING: An illegal reflective access operation has occurred
```

So I can no longer run the tests in this module.

**Comment by utzcoz** [comment]
@bj0 You can add `@aar` to AXT dependency to try to fix it, e.g. `api "androidx.test:monitor:$axtMonitorVersion@aar"`.

**Comment by utzcoz** [comment]
> @bj0 You can add `@aar` to AXT dependency to try to fix it, e.g. `api "androidx.test:monitor:$axtMonitorVersion@aar"`.

Please follow this approach to try to fix it. And feel freen to reopen this issue if it doesn't work.
