### ISSUE TITLE
Resources.NotFoundException(String, Exception) Only added in N+

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#3283]
As reported by @jkasten2 we cannot call String, Exception constructor on SDK < N as it doesn't exist

Also for those on robolectric:3.4-rc5 you will get an error like this without it.

```
java.lang.NoSuchMethodError: android.content.res.Resources$NotFoundException.<init>(Ljava/lang/String;Ljava/lang/Exception;)V
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:72)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:293)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:222)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
```

**Comment by BrantApps** [comment]
Hey @jongerrish! It looks like you are almost there with the triple-whammy of AS3.0/AGP3.0/Gradle4.0! In my testing/experimenting, I've managed to get as far as this exception which I think is as far as I'm going to get (most tests are running green).

Would you be able to advise if there is something I can do to workaround this? Happy to PR if you can give me a head start! Looking forward to my first green build with v3.4 and all the new tooling!

**Comment by ngoctranfire** [comment]
This problem is still affecting me. Also, I noticed that the 3.5-SNAPSHOT just doesn't exist so I can't even get these fixes....

**Comment by BrantApps** [comment]
Heads up @ngoctranfire - after I upgrade the tooling to use the new unit testing options and removed the ````constants=BuildConfig.class```` as described in the [migration docs](http://robolectric.org/getting-started/) it stopped happening! Give it a go...

**Comment by ngoctranfire** [comment]
@BrantApps I also removed the constants=BuildConfig.class as instructed as well too...
